// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pkg/pb/course/course.proto

package course

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCoursesRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OnlyPublic           bool     `protobuf:"varint,2,opt,name=only_public,json=onlyPublic,proto3" json:"only_public,omitempty"`
	OnlyMine             bool     `protobuf:"varint,3,opt,name=only_mine,json=onlyMine,proto3" json:"only_mine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCoursesRequest) Reset()         { *m = ListCoursesRequest{} }
func (m *ListCoursesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCoursesRequest) ProtoMessage()    {}
func (*ListCoursesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{0}
}

func (m *ListCoursesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCoursesRequest.Unmarshal(m, b)
}
func (m *ListCoursesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCoursesRequest.Marshal(b, m, deterministic)
}
func (m *ListCoursesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCoursesRequest.Merge(m, src)
}
func (m *ListCoursesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCoursesRequest.Size(m)
}
func (m *ListCoursesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCoursesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCoursesRequest proto.InternalMessageInfo

func (m *ListCoursesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListCoursesRequest) GetOnlyPublic() bool {
	if m != nil {
		return m.OnlyPublic
	}
	return false
}

func (m *ListCoursesRequest) GetOnlyMine() bool {
	if m != nil {
		return m.OnlyMine
	}
	return false
}

type ListCoursesReply struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string               `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64                `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool                 `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListCoursesReply) Reset()         { *m = ListCoursesReply{} }
func (m *ListCoursesReply) String() string { return proto.CompactTextString(m) }
func (*ListCoursesReply) ProtoMessage()    {}
func (*ListCoursesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{1}
}

func (m *ListCoursesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCoursesReply.Unmarshal(m, b)
}
func (m *ListCoursesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCoursesReply.Marshal(b, m, deterministic)
}
func (m *ListCoursesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCoursesReply.Merge(m, src)
}
func (m *ListCoursesReply) XXX_Size() int {
	return xxx_messageInfo_ListCoursesReply.Size(m)
}
func (m *ListCoursesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCoursesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListCoursesReply proto.InternalMessageInfo

func (m *ListCoursesReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListCoursesReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListCoursesReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListCoursesReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *ListCoursesReply) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ListCoursesReply) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ListCoursesReply) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *ListCoursesReply) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type GetCourseRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCourseRequest) Reset()         { *m = GetCourseRequest{} }
func (m *GetCourseRequest) String() string { return proto.CompactTextString(m) }
func (*GetCourseRequest) ProtoMessage()    {}
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{2}
}

func (m *GetCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseRequest.Unmarshal(m, b)
}
func (m *GetCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseRequest.Marshal(b, m, deterministic)
}
func (m *GetCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseRequest.Merge(m, src)
}
func (m *GetCourseRequest) XXX_Size() int {
	return xxx_messageInfo_GetCourseRequest.Size(m)
}
func (m *GetCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseRequest proto.InternalMessageInfo

func (m *GetCourseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetCourseReply struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string               `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64                `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool                 `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetCourseReply) Reset()         { *m = GetCourseReply{} }
func (m *GetCourseReply) String() string { return proto.CompactTextString(m) }
func (*GetCourseReply) ProtoMessage()    {}
func (*GetCourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{3}
}

func (m *GetCourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCourseReply.Unmarshal(m, b)
}
func (m *GetCourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCourseReply.Marshal(b, m, deterministic)
}
func (m *GetCourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCourseReply.Merge(m, src)
}
func (m *GetCourseReply) XXX_Size() int {
	return xxx_messageInfo_GetCourseReply.Size(m)
}
func (m *GetCourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCourseReply proto.InternalMessageInfo

func (m *GetCourseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetCourseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetCourseReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetCourseReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *GetCourseReply) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *GetCourseReply) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetCourseReply) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *GetCourseReply) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CreateCourseRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string   `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool     `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCourseRequest) Reset()         { *m = CreateCourseRequest{} }
func (m *CreateCourseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCourseRequest) ProtoMessage()    {}
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{4}
}

func (m *CreateCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCourseRequest.Unmarshal(m, b)
}
func (m *CreateCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCourseRequest.Marshal(b, m, deterministic)
}
func (m *CreateCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCourseRequest.Merge(m, src)
}
func (m *CreateCourseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCourseRequest.Size(m)
}
func (m *CreateCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCourseRequest proto.InternalMessageInfo

func (m *CreateCourseRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCourseRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateCourseRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateCourseRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateCourseRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateCourseRequest) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

type CreateCourseReply struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string               `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64                `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool                 `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateCourseReply) Reset()         { *m = CreateCourseReply{} }
func (m *CreateCourseReply) String() string { return proto.CompactTextString(m) }
func (*CreateCourseReply) ProtoMessage()    {}
func (*CreateCourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{5}
}

func (m *CreateCourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCourseReply.Unmarshal(m, b)
}
func (m *CreateCourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCourseReply.Marshal(b, m, deterministic)
}
func (m *CreateCourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCourseReply.Merge(m, src)
}
func (m *CreateCourseReply) XXX_Size() int {
	return xxx_messageInfo_CreateCourseReply.Size(m)
}
func (m *CreateCourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCourseReply proto.InternalMessageInfo

func (m *CreateCourseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateCourseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCourseReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateCourseReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateCourseReply) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *CreateCourseReply) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateCourseReply) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *CreateCourseReply) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type UpdateCourseRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64    `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool     `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCourseRequest) Reset()         { *m = UpdateCourseRequest{} }
func (m *UpdateCourseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCourseRequest) ProtoMessage()    {}
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{6}
}

func (m *UpdateCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCourseRequest.Unmarshal(m, b)
}
func (m *UpdateCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCourseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCourseRequest.Merge(m, src)
}
func (m *UpdateCourseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCourseRequest.Size(m)
}
func (m *UpdateCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCourseRequest proto.InternalMessageInfo

func (m *UpdateCourseRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCourseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateCourseRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateCourseRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateCourseRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpdateCourseRequest) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateCourseRequest) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

type UpdateCourseReply struct {
	Uuid                 string               `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string               `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Image                string               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64                `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublic             bool                 `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateCourseReply) Reset()         { *m = UpdateCourseReply{} }
func (m *UpdateCourseReply) String() string { return proto.CompactTextString(m) }
func (*UpdateCourseReply) ProtoMessage()    {}
func (*UpdateCourseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{7}
}

func (m *UpdateCourseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCourseReply.Unmarshal(m, b)
}
func (m *UpdateCourseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCourseReply.Marshal(b, m, deterministic)
}
func (m *UpdateCourseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCourseReply.Merge(m, src)
}
func (m *UpdateCourseReply) XXX_Size() int {
	return xxx_messageInfo_UpdateCourseReply.Size(m)
}
func (m *UpdateCourseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCourseReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCourseReply proto.InternalMessageInfo

func (m *UpdateCourseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateCourseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCourseReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateCourseReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateCourseReply) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpdateCourseReply) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateCourseReply) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *UpdateCourseReply) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DeleteCourseRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCourseRequest) Reset()         { *m = DeleteCourseRequest{} }
func (m *DeleteCourseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCourseRequest) ProtoMessage()    {}
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a11be236314637ae, []int{8}
}

func (m *DeleteCourseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCourseRequest.Unmarshal(m, b)
}
func (m *DeleteCourseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCourseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCourseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCourseRequest.Merge(m, src)
}
func (m *DeleteCourseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCourseRequest.Size(m)
}
func (m *DeleteCourseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCourseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCourseRequest proto.InternalMessageInfo

func (m *DeleteCourseRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteCourseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCoursesRequest)(nil), "course.ListCoursesRequest")
	proto.RegisterType((*ListCoursesReply)(nil), "course.ListCoursesReply")
	proto.RegisterType((*GetCourseRequest)(nil), "course.GetCourseRequest")
	proto.RegisterType((*GetCourseReply)(nil), "course.GetCourseReply")
	proto.RegisterType((*CreateCourseRequest)(nil), "course.CreateCourseRequest")
	proto.RegisterType((*CreateCourseReply)(nil), "course.CreateCourseReply")
	proto.RegisterType((*UpdateCourseRequest)(nil), "course.UpdateCourseRequest")
	proto.RegisterType((*UpdateCourseReply)(nil), "course.UpdateCourseReply")
	proto.RegisterType((*DeleteCourseRequest)(nil), "course.DeleteCourseRequest")
}

func init() {
	proto.RegisterFile("internal/pkg/pb/course/course.proto", fileDescriptor_a11be236314637ae)
}

var fileDescriptor_a11be236314637ae = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x56, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xae, 0xfb, 0x91, 0xb5, 0x6f, 0x2b, 0x34, 0x5c, 0x34, 0x42, 0x7a, 0x58, 0x15, 0x24, 0xd4,
	0x0b, 0x09, 0x1a, 0x27, 0x4e, 0xa8, 0x2b, 0xd3, 0x40, 0x62, 0xd2, 0x14, 0xc1, 0x85, 0x4b, 0x95,
	0xa6, 0x26, 0xb3, 0x9a, 0x0f, 0xe3, 0xd8, 0x87, 0xfe, 0x2c, 0x7e, 0x04, 0x3f, 0x87, 0x5f, 0x80,
	0x40, 0x28, 0x76, 0xd3, 0x26, 0x6b, 0x36, 0x21, 0x71, 0xd8, 0xa1, 0xa7, 0xf6, 0xfd, 0xf0, 0xe3,
	0x3e, 0xcf, 0x63, 0xbf, 0x2e, 0x3c, 0xa7, 0x89, 0x20, 0x3c, 0xf1, 0x23, 0x97, 0xad, 0x42, 0x97,
	0x2d, 0xdc, 0x20, 0x95, 0x3c, 0x23, 0x9b, 0x0f, 0x87, 0xf1, 0x54, 0xa4, 0xd8, 0xd0, 0x91, 0x75,
	0x1a, 0xa6, 0x69, 0x18, 0x11, 0x57, 0x65, 0x17, 0xf2, 0xab, 0x2b, 0x68, 0x4c, 0x32, 0xe1, 0xc7,
	0x4c, 0x37, 0x5a, 0xa3, 0xdb, 0x0d, 0x24, 0x66, 0x62, 0xad, 0x8b, 0xf6, 0x0a, 0xf0, 0x47, 0x9a,
	0x89, 0x99, 0xc2, 0xca, 0x3c, 0xf2, 0x4d, 0x92, 0x4c, 0xe0, 0xa7, 0x70, 0x24, 0x33, 0xc2, 0xe7,
	0x74, 0x69, 0xa2, 0x31, 0x9a, 0xf4, 0x3c, 0x23, 0x0f, 0x3f, 0x2c, 0xf1, 0x29, 0xf4, 0xd3, 0x24,
	0x5a, 0xcf, 0x99, 0x5c, 0x44, 0x34, 0x30, 0x9b, 0x63, 0x34, 0xe9, 0x7a, 0x90, 0xa7, 0xae, 0x55,
	0x06, 0x8f, 0xa0, 0xa7, 0x1a, 0x62, 0x9a, 0x10, 0xb3, 0xa5, 0xca, 0xdd, 0x3c, 0x71, 0x45, 0x13,
	0x62, 0xff, 0x46, 0x70, 0x5c, 0xd9, 0x8d, 0x45, 0x6b, 0x8c, 0xa1, 0x2d, 0xe5, 0x76, 0x23, 0xf5,
	0xbd, 0xbc, 0x7f, 0xb3, 0xb2, 0xff, 0x13, 0xe8, 0x08, 0x2a, 0x22, 0x0d, 0xdd, 0xf3, 0x74, 0x80,
	0x6d, 0x18, 0xd0, 0x44, 0xf0, 0x74, 0x29, 0x03, 0x41, 0xd3, 0xc4, 0x6c, 0xab, 0x62, 0x25, 0x97,
	0xaf, 0xa4, 0xb1, 0x1f, 0x12, 0xb3, 0xa3, 0x57, 0xaa, 0x20, 0xcf, 0x32, 0x4e, 0x03, 0x62, 0x1a,
	0x63, 0x34, 0x69, 0x79, 0x3a, 0xc8, 0x49, 0xd0, 0xac, 0xe0, 0x78, 0xa4, 0x49, 0xd0, 0x6c, 0xc3,
	0xf0, 0x0d, 0x40, 0xc0, 0x89, 0x2f, 0xc8, 0x72, 0xee, 0x0b, 0xb3, 0x3b, 0x46, 0x93, 0xfe, 0x99,
	0xe5, 0x68, 0x8d, 0x9d, 0x42, 0x63, 0xe7, 0x53, 0x61, 0x82, 0xd7, 0xdb, 0x74, 0x4f, 0x85, 0xfd,
	0x02, 0x8e, 0x2f, 0xc9, 0x86, 0x7d, 0x21, 0x75, 0x0d, 0x7d, 0xfb, 0x17, 0x82, 0x47, 0xa5, 0xc6,
	0x03, 0x53, 0xe9, 0x3b, 0x82, 0xe1, 0x4c, 0x45, 0x55, 0xa5, 0xee, 0x3c, 0x94, 0x5b, 0xba, 0xcd,
	0xfb, 0xe8, 0xb6, 0xee, 0xa3, 0xdb, 0xae, 0xa5, 0xdb, 0xb9, 0x93, 0xae, 0x51, 0xa5, 0x6b, 0xff,
	0x41, 0xf0, 0xb8, 0xfa, 0x9b, 0x0f, 0xcc, 0xb4, 0x1f, 0x08, 0x86, 0x9f, 0xd9, 0xf2, 0xdf, 0x4d,
	0x2b, 0xb4, 0x69, 0x96, 0xb4, 0x79, 0x78, 0x09, 0x94, 0x91, 0x55, 0x1e, 0x07, 0x66, 0xe4, 0x39,
	0x0c, 0xdf, 0x91, 0x88, 0xfc, 0x8f, 0x8f, 0x67, 0x3f, 0x9b, 0x60, 0xe8, 0xe5, 0xf8, 0x12, 0xfa,
	0xa5, 0x89, 0x8f, 0x2d, 0x67, 0xf3, 0x86, 0xed, 0x3f, 0x3a, 0x96, 0x59, 0x5b, 0x63, 0xd1, 0xda,
	0x6e, 0xbc, 0x42, 0xf8, 0x2d, 0xf4, 0xb6, 0x23, 0x11, 0x6f, 0x5b, 0x6f, 0x8f, 0x53, 0xeb, 0xa4,
	0xa6, 0xa2, 0x20, 0xf0, 0x7b, 0x18, 0x94, 0x6f, 0x28, 0x1e, 0x15, 0x9d, 0x35, 0xb3, 0xc6, 0x7a,
	0x56, 0x5f, 0xdc, 0x22, 0x95, 0x8f, 0xc8, 0x0e, 0xa9, 0xe6, 0x02, 0xec, 0x90, 0xf6, 0x4e, 0x95,
	0xdd, 0xc0, 0x17, 0x30, 0x28, 0x8b, 0xbd, 0x43, 0xaa, 0xb1, 0xc0, 0x3a, 0xd9, 0x33, 0xf0, 0x22,
	0x7f, 0xc8, 0xed, 0xc6, 0xf9, 0xec, 0xcb, 0x34, 0xa4, 0xe2, 0x46, 0x2e, 0x9c, 0x20, 0x8d, 0xdd,
	0x69, 0x26, 0x6f, 0xfc, 0x97, 0xbe, 0x7b, 0xcd, 0xd3, 0x90, 0xfb, 0x71, 0x4c, 0x93, 0x50, 0x03,
	0x5d, 0xf9, 0x7c, 0x45, 0x84, 0x5b, 0xff, 0xe7, 0x62, 0x61, 0x28, 0xd8, 0xd7, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0x82, 0x58, 0x18, 0x7d, 0x08, 0x00, 0x00,
}
