// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pkg/pb/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListUsersRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{0}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListUsersReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Permission           string   `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersReply) Reset()         { *m = ListUsersReply{} }
func (m *ListUsersReply) String() string { return proto.CompactTextString(m) }
func (*ListUsersReply) ProtoMessage()    {}
func (*ListUsersReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{1}
}

func (m *ListUsersReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersReply.Unmarshal(m, b)
}
func (m *ListUsersReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersReply.Marshal(b, m, deterministic)
}
func (m *ListUsersReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersReply.Merge(m, src)
}
func (m *ListUsersReply) XXX_Size() int {
	return xxx_messageInfo_ListUsersReply.Size(m)
}
func (m *ListUsersReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersReply proto.InternalMessageInfo

func (m *ListUsersReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListUsersReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListUsersReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *ListUsersReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListUsersReply) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type GetUserRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetUserReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Permission           string   `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReply) Reset()         { *m = GetUserReply{} }
func (m *GetUserReply) String() string { return proto.CompactTextString(m) }
func (*GetUserReply) ProtoMessage()    {}
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{3}
}

func (m *GetUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReply.Unmarshal(m, b)
}
func (m *GetUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReply.Marshal(b, m, deterministic)
}
func (m *GetUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReply.Merge(m, src)
}
func (m *GetUserReply) XXX_Size() int {
	return xxx_messageInfo_GetUserReply.Size(m)
}
func (m *GetUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReply proto.InternalMessageInfo

func (m *GetUserReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUserReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *GetUserReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserReply) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,2,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{4}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Permission           string   `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{5}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

func (m *CreateUserReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateUserReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateUserReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserReply) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type UpdateUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,3,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Uuid                 string   `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type UpdateUserReply struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Introduction         string   `protobuf:"bytes,4,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Permission           string   `protobuf:"bytes,6,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReply) Reset()         { *m = UpdateUserReply{} }
func (m *UpdateUserReply) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReply) ProtoMessage()    {}
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{7}
}

func (m *UpdateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReply.Unmarshal(m, b)
}
func (m *UpdateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReply.Marshal(b, m, deterministic)
}
func (m *UpdateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReply.Merge(m, src)
}
func (m *UpdateUserReply) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReply.Size(m)
}
func (m *UpdateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReply proto.InternalMessageInfo

func (m *UpdateUserReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateUserReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateUserReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateUserReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserReply) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type DeleteUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adc174aef4d77d94, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteUserRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "user.ListUsersRequest")
	proto.RegisterType((*ListUsersReply)(nil), "user.ListUsersReply")
	proto.RegisterType((*GetUserRequest)(nil), "user.GetUserRequest")
	proto.RegisterType((*GetUserReply)(nil), "user.GetUserReply")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "user.CreateUserReply")
	proto.RegisterType((*UpdateUserRequest)(nil), "user.UpdateUserRequest")
	proto.RegisterType((*UpdateUserReply)(nil), "user.UpdateUserReply")
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
}

func init() {
	proto.RegisterFile("internal/pkg/pb/user/user.proto", fileDescriptor_adc174aef4d77d94)
}

var fileDescriptor_adc174aef4d77d94 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0xc0, 0x9b, 0x36, 0x2d, 0xec, 0x69, 0x1a, 0xd4, 0x1a, 0xa3, 0x0a, 0x12, 0x20, 0x8b, 0xc3,
	0x2e, 0x24, 0x08, 0xc4, 0x71, 0x4c, 0x63, 0x20, 0x2e, 0x20, 0xa1, 0x49, 0xbb, 0x70, 0x73, 0xd7,
	0x47, 0x66, 0x35, 0x89, 0x8d, 0xff, 0x08, 0xf5, 0xc0, 0x77, 0x40, 0x7c, 0x09, 0xc4, 0x87, 0xe0,
	0xbb, 0x21, 0x3b, 0x4d, 0x9a, 0x26, 0x5d, 0xc5, 0x61, 0x87, 0x5e, 0x22, 0xfb, 0xf9, 0xbd, 0xf8,
	0xa7, 0x9f, 0xed, 0x07, 0x4f, 0x78, 0x61, 0x50, 0x15, 0x2c, 0x4b, 0xe4, 0x3c, 0x4d, 0xe4, 0x34,
	0xb1, 0x1a, 0x95, 0xff, 0xc4, 0x52, 0x09, 0x23, 0x48, 0xe8, 0xc6, 0xd1, 0xa3, 0x54, 0x88, 0x34,
	0xc3, 0xc4, 0xc7, 0xa6, 0xf6, 0x6b, 0x82, 0xb9, 0x34, 0x8b, 0x32, 0x85, 0x1e, 0xc3, 0xfd, 0x8f,
	0x5c, 0x9b, 0x4b, 0x8d, 0x4a, 0x5f, 0xe0, 0x37, 0x8b, 0xda, 0x90, 0x43, 0x18, 0x1a, 0x31, 0xc7,
	0x62, 0x12, 0x3c, 0x0d, 0x8e, 0xf7, 0x2e, 0xca, 0x09, 0xfd, 0x15, 0xc0, 0x41, 0x23, 0x55, 0x66,
	0x0b, 0x42, 0x20, 0xb4, 0x96, 0xcf, 0x96, 0x79, 0x7e, 0xec, 0x62, 0x05, 0xcb, 0x71, 0xd2, 0x2f,
	0x63, 0x6e, 0x4c, 0x28, 0xec, 0xf3, 0xc2, 0x28, 0x31, 0xb3, 0x57, 0x86, 0x8b, 0x62, 0x32, 0xf0,
	0x6b, 0x6b, 0x31, 0xb7, 0x29, 0xe6, 0x8c, 0x67, 0x93, 0xb0, 0xdc, 0xd4, 0x4f, 0xc8, 0x63, 0x00,
	0x89, 0x2a, 0xe7, 0x5a, 0xbb, 0xba, 0xa1, 0x5f, 0x6a, 0x44, 0xe8, 0x33, 0x38, 0xf8, 0x80, 0x1e,
	0xa9, 0x82, 0xdf, 0xc0, 0x44, 0x7f, 0x06, 0xb0, 0x5f, 0xa7, 0xed, 0x06, 0xf8, 0x0f, 0x18, 0x9f,
	0x2b, 0x64, 0x06, 0x5b, 0xec, 0x1e, 0x21, 0xd8, 0x82, 0xd0, 0xdf, 0x86, 0x30, 0x68, 0x22, 0x44,
	0x70, 0x57, 0x32, 0xad, 0xbf, 0x0b, 0x35, 0x5b, 0xb2, 0xd5, 0x73, 0xfa, 0x27, 0x80, 0x7b, 0xcd,
	0xfd, 0x9d, 0x94, 0x8d, 0xc7, 0x5e, 0xab, 0xea, 0x6f, 0x50, 0x35, 0xd8, 0xc2, 0x19, 0x6e, 0xe3,
	0x1c, 0xde, 0xac, 0x6a, 0xd4, 0x51, 0xf5, 0x3b, 0x80, 0xf1, 0xa5, 0x9c, 0xb5, 0x5c, 0xdd, 0x48,
	0x7b, 0x8b, 0x87, 0xd8, 0x34, 0x38, 0x5c, 0x37, 0x58, 0x7b, 0x19, 0x35, 0xee, 0x99, 0xb3, 0xda,
	0x24, 0xdd, 0x65, 0xab, 0x27, 0x30, 0x7e, 0x87, 0x19, 0xfe, 0xa7, 0xd4, 0x36, 0xec, 0xcb, 0xbf,
	0x7d, 0x08, 0x5d, 0x25, 0x39, 0x81, 0xbd, 0xba, 0x2b, 0x90, 0xa3, 0xd8, 0x77, 0x9f, 0x76, 0x47,
	0x89, 0x0e, 0x3b, 0x71, 0x99, 0x2d, 0x68, 0xef, 0x45, 0x40, 0x5e, 0xc3, 0x9d, 0xe5, 0xcb, 0x24,
	0xcb, 0xa4, 0xf5, 0xf7, 0x1c, 0x91, 0x56, 0xd4, 0x17, 0x92, 0x37, 0x00, 0xab, 0xeb, 0x4b, 0x1e,
	0x96, 0x39, 0x9d, 0x07, 0x15, 0x3d, 0xe8, 0x2e, 0xd4, 0xf5, 0xab, 0x83, 0xaa, 0xea, 0x3b, 0x97,
	0xac, 0xaa, 0x6f, 0x9d, 0x29, 0xed, 0x91, 0x53, 0x80, 0x95, 0xbd, 0xaa, 0xbe, 0xe3, 0x33, 0x3a,
	0x8a, 0xcb, 0xde, 0x1b, 0x57, 0xbd, 0x37, 0x7e, 0xef, 0x7a, 0x2f, 0xed, 0xbd, 0x3d, 0xfb, 0x72,
	0x9a, 0x72, 0x73, 0x6d, 0xa7, 0xf1, 0x95, 0xc8, 0x93, 0x33, 0x6d, 0xaf, 0xd9, 0x73, 0x96, 0x7c,
	0x56, 0x22, 0x55, 0x2c, 0xcf, 0x79, 0x91, 0x9e, 0x0b, 0xab, 0x34, 0x7e, 0x62, 0x6a, 0x8e, 0x26,
	0xd9, 0xd4, 0xe8, 0xa7, 0x23, 0xff, 0xd3, 0x57, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x93, 0xde,
	0xaa, 0x74, 0x07, 0x06, 0x00, 0x00,
}
