import React, { useState } from 'react';
import { TableContainer, Table, TableHead, TableRow, TableCell, TableBody, Paper } from '@mui/material';
import { Case } from '../config/Type';

function TestCaseTable(props: any) {
  const { cases } = props;

  return (
    <TableContainer component={Paper}>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCell>Test Case Number</TableCell>
            <TableCell align="left">Input</TableCell>
            <TableCell align="left">Output generated by Answer Code</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {cases === null && (
            <TableRow key="empty" sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
              <TableCell component="th" scope="row">
                No Test Case
              </TableCell>
              <TableCell align="left">No Data</TableCell>
              <TableCell align="left">No Data</TableCell>
            </TableRow>
          )}
          {cases !== null &&
            cases.map((testCase: Case, index: number) => (
              <TableRow key={testCase.uuid} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
                <TableCell component="th" scope="row">
                  Test Case {index + 1}
                </TableCell>
                <TableCell align="left">
                  {testCase.input.split('\n').map((line, idx) => (
                    <p key={idx}>{line}</p>
                  ))}
                </TableCell>
                <TableCell align="left">
                  {testCase.output.split('\n').map((line, idx) => (
                    <p key={idx}>{line}</p>
                  ))}
                </TableCell>
              </TableRow>
            ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
}

export default TestCaseTable;
