// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pkg/pb/case/case.proto

package _case

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCasesRequest struct {
	LessonId             string   `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCasesRequest) Reset()         { *m = ListCasesRequest{} }
func (m *ListCasesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCasesRequest) ProtoMessage()    {}
func (*ListCasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{0}
}

func (m *ListCasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCasesRequest.Unmarshal(m, b)
}
func (m *ListCasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCasesRequest.Marshal(b, m, deterministic)
}
func (m *ListCasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCasesRequest.Merge(m, src)
}
func (m *ListCasesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCasesRequest.Size(m)
}
func (m *ListCasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCasesRequest proto.InternalMessageInfo

func (m *ListCasesRequest) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

type ListCasesReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId             string   `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCasesReply) Reset()         { *m = ListCasesReply{} }
func (m *ListCasesReply) String() string { return proto.CompactTextString(m) }
func (*ListCasesReply) ProtoMessage()    {}
func (*ListCasesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{1}
}

func (m *ListCasesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCasesReply.Unmarshal(m, b)
}
func (m *ListCasesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCasesReply.Marshal(b, m, deterministic)
}
func (m *ListCasesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCasesReply.Merge(m, src)
}
func (m *ListCasesReply) XXX_Size() int {
	return xxx_messageInfo_ListCasesReply.Size(m)
}
func (m *ListCasesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCasesReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListCasesReply proto.InternalMessageInfo

func (m *ListCasesReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListCasesReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListCasesReply) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *ListCasesReply) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *ListCasesReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type GetCaseRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCaseRequest) Reset()         { *m = GetCaseRequest{} }
func (m *GetCaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetCaseRequest) ProtoMessage()    {}
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{2}
}

func (m *GetCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaseRequest.Unmarshal(m, b)
}
func (m *GetCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaseRequest.Marshal(b, m, deterministic)
}
func (m *GetCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaseRequest.Merge(m, src)
}
func (m *GetCaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetCaseRequest.Size(m)
}
func (m *GetCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaseRequest proto.InternalMessageInfo

func (m *GetCaseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetCaseReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId             string   `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCaseReply) Reset()         { *m = GetCaseReply{} }
func (m *GetCaseReply) String() string { return proto.CompactTextString(m) }
func (*GetCaseReply) ProtoMessage()    {}
func (*GetCaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{3}
}

func (m *GetCaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCaseReply.Unmarshal(m, b)
}
func (m *GetCaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCaseReply.Marshal(b, m, deterministic)
}
func (m *GetCaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCaseReply.Merge(m, src)
}
func (m *GetCaseReply) XXX_Size() int {
	return xxx_messageInfo_GetCaseReply.Size(m)
}
func (m *GetCaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetCaseReply proto.InternalMessageInfo

func (m *GetCaseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetCaseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetCaseReply) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *GetCaseReply) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *GetCaseReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type CreateCaseRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LessonId             string   `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCaseRequest) Reset()         { *m = CreateCaseRequest{} }
func (m *CreateCaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCaseRequest) ProtoMessage()    {}
func (*CreateCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{4}
}

func (m *CreateCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCaseRequest.Unmarshal(m, b)
}
func (m *CreateCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCaseRequest.Marshal(b, m, deterministic)
}
func (m *CreateCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCaseRequest.Merge(m, src)
}
func (m *CreateCaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCaseRequest.Size(m)
}
func (m *CreateCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCaseRequest proto.InternalMessageInfo

func (m *CreateCaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateCaseRequest) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *CreateCaseRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *CreateCaseRequest) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type CreateCaseReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId             string   `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCaseReply) Reset()         { *m = CreateCaseReply{} }
func (m *CreateCaseReply) String() string { return proto.CompactTextString(m) }
func (*CreateCaseReply) ProtoMessage()    {}
func (*CreateCaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{5}
}

func (m *CreateCaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCaseReply.Unmarshal(m, b)
}
func (m *CreateCaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCaseReply.Marshal(b, m, deterministic)
}
func (m *CreateCaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCaseReply.Merge(m, src)
}
func (m *CreateCaseReply) XXX_Size() int {
	return xxx_messageInfo_CreateCaseReply.Size(m)
}
func (m *CreateCaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCaseReply proto.InternalMessageInfo

func (m *CreateCaseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateCaseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCaseReply) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *CreateCaseReply) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *CreateCaseReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type UpdateCaseRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId             string   `protobuf:"bytes,4,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,6,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCaseRequest) Reset()         { *m = UpdateCaseRequest{} }
func (m *UpdateCaseRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCaseRequest) ProtoMessage()    {}
func (*UpdateCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{6}
}

func (m *UpdateCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCaseRequest.Unmarshal(m, b)
}
func (m *UpdateCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCaseRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCaseRequest.Merge(m, src)
}
func (m *UpdateCaseRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCaseRequest.Size(m)
}
func (m *UpdateCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCaseRequest proto.InternalMessageInfo

func (m *UpdateCaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateCaseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateCaseRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCaseRequest) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *UpdateCaseRequest) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *UpdateCaseRequest) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type UpdateCaseReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId             string   `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Input                string   `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	Output               string   `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCaseReply) Reset()         { *m = UpdateCaseReply{} }
func (m *UpdateCaseReply) String() string { return proto.CompactTextString(m) }
func (*UpdateCaseReply) ProtoMessage()    {}
func (*UpdateCaseReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{7}
}

func (m *UpdateCaseReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCaseReply.Unmarshal(m, b)
}
func (m *UpdateCaseReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCaseReply.Marshal(b, m, deterministic)
}
func (m *UpdateCaseReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCaseReply.Merge(m, src)
}
func (m *UpdateCaseReply) XXX_Size() int {
	return xxx_messageInfo_UpdateCaseReply.Size(m)
}
func (m *UpdateCaseReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCaseReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCaseReply proto.InternalMessageInfo

func (m *UpdateCaseReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateCaseReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateCaseReply) GetLessonId() string {
	if m != nil {
		return m.LessonId
	}
	return ""
}

func (m *UpdateCaseReply) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *UpdateCaseReply) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type DeleteCaseRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCaseRequest) Reset()         { *m = DeleteCaseRequest{} }
func (m *DeleteCaseRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCaseRequest) ProtoMessage()    {}
func (*DeleteCaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d85c28a859cc37d, []int{8}
}

func (m *DeleteCaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCaseRequest.Unmarshal(m, b)
}
func (m *DeleteCaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCaseRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCaseRequest.Merge(m, src)
}
func (m *DeleteCaseRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCaseRequest.Size(m)
}
func (m *DeleteCaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCaseRequest proto.InternalMessageInfo

func (m *DeleteCaseRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteCaseRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListCasesRequest)(nil), "case.ListCasesRequest")
	proto.RegisterType((*ListCasesReply)(nil), "case.ListCasesReply")
	proto.RegisterType((*GetCaseRequest)(nil), "case.GetCaseRequest")
	proto.RegisterType((*GetCaseReply)(nil), "case.GetCaseReply")
	proto.RegisterType((*CreateCaseRequest)(nil), "case.CreateCaseRequest")
	proto.RegisterType((*CreateCaseReply)(nil), "case.CreateCaseReply")
	proto.RegisterType((*UpdateCaseRequest)(nil), "case.UpdateCaseRequest")
	proto.RegisterType((*UpdateCaseReply)(nil), "case.UpdateCaseReply")
	proto.RegisterType((*DeleteCaseRequest)(nil), "case.DeleteCaseRequest")
}

func init() {
	proto.RegisterFile("internal/pkg/pb/case/case.proto", fileDescriptor_8d85c28a859cc37d)
}

var fileDescriptor_8d85c28a859cc37d = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0x13, 0x27, 0x25, 0x23, 0x54, 0xc8, 0x2a, 0xa4, 0x95, 0x7b, 0x00, 0x59, 0x1c, 0xb8,
	0xe0, 0x45, 0x20, 0x8e, 0xa5, 0x2a, 0x05, 0xa1, 0x4a, 0x45, 0x42, 0x95, 0xb8, 0x70, 0x41, 0xeb,
	0x7a, 0x70, 0xac, 0xd8, 0xde, 0xc5, 0xbb, 0x7b, 0xc8, 0x0f, 0x20, 0xf8, 0x0c, 0x3e, 0x84, 0x7f,
	0x43, 0xde, 0x8d, 0x1d, 0x3b, 0x76, 0x24, 0xc4, 0x25, 0x17, 0xcb, 0xf3, 0x76, 0xde, 0xcc, 0xd3,
	0xdb, 0x9d, 0x81, 0xc7, 0x49, 0xae, 0xb0, 0xc8, 0x59, 0x4a, 0xc5, 0x2a, 0xa6, 0x22, 0xa4, 0x77,
	0x4c, 0xa2, 0xf9, 0x04, 0xa2, 0xe0, 0x8a, 0x13, 0xb7, 0xfc, 0xf7, 0xce, 0x62, 0xce, 0xe3, 0x14,
	0xa9, 0xc1, 0x42, 0xfd, 0x8d, 0x62, 0x26, 0xd4, 0xda, 0xa6, 0xf8, 0x14, 0x1e, 0xde, 0x24, 0x52,
	0x5d, 0x31, 0x89, 0xf2, 0x16, 0xbf, 0x6b, 0x94, 0x8a, 0x9c, 0xc1, 0x34, 0x45, 0x29, 0x79, 0xfe,
	0x35, 0x89, 0x4e, 0x9d, 0x27, 0xce, 0xb3, 0xe9, 0xed, 0x3d, 0x0b, 0x5c, 0x47, 0xfe, 0x4f, 0x07,
	0x8e, 0x1b, 0x0c, 0x91, 0xae, 0x09, 0x01, 0x57, 0xeb, 0x3a, 0xd5, 0xfc, 0x93, 0x13, 0x38, 0xd2,
	0x12, 0x8b, 0xb2, 0xc2, 0xd0, 0xc0, 0x93, 0x32, 0xbc, 0x8e, 0xda, 0xc5, 0x47, 0xed, 0xe2, 0x64,
	0x0e, 0xe3, 0x24, 0x17, 0x5a, 0x9d, 0xba, 0xe6, 0xc0, 0x06, 0x64, 0x01, 0x13, 0xae, 0x55, 0x09,
	0x8f, 0x6d, 0x29, 0x1b, 0xf9, 0x4f, 0xe1, 0xf8, 0x03, 0x1a, 0x21, 0x95, 0xf2, 0x1e, 0x25, 0xfe,
	0x0f, 0x07, 0xee, 0xd7, 0x69, 0x87, 0x94, 0xab, 0x60, 0x76, 0x55, 0x20, 0x53, 0xd8, 0x54, 0x3c,
	0x87, 0xb1, 0xe2, 0x2b, 0xcc, 0x37, 0x6a, 0x6c, 0xd0, 0xee, 0x3a, 0xdc, 0xd7, 0x75, 0xd4, 0xdf,
	0xd5, 0x6d, 0x75, 0xfd, 0xe5, 0xc0, 0x83, 0x66, 0xdb, 0x43, 0x3a, 0xf0, 0xdb, 0x81, 0xd9, 0x67,
	0x11, 0xfd, 0x93, 0x05, 0x95, 0xc6, 0x61, 0xbf, 0xc6, 0xd1, 0x7e, 0x8d, 0xee, 0x3e, 0x8d, 0xe3,
	0x7e, 0x8d, 0x93, 0x8e, 0x5f, 0x4d, 0x8d, 0x87, 0xf4, 0xeb, 0x1c, 0x66, 0xef, 0x30, 0xc5, 0xff,
	0xb4, 0xeb, 0xe5, 0x9f, 0x21, 0xb8, 0x25, 0x93, 0x9c, 0xc3, 0xb4, 0x1e, 0x59, 0xb2, 0x08, 0xcc,
	0x86, 0xd8, 0x9d, 0x7a, 0x6f, 0xde, 0xc1, 0x45, 0xba, 0xf6, 0x07, 0x2f, 0x1c, 0xf2, 0x1a, 0x8e,
	0x36, 0x03, 0x44, 0x36, 0x49, 0xed, 0xb1, 0xf3, 0xc8, 0x0e, 0x6a, 0x88, 0xe4, 0x0d, 0xc0, 0xf6,
	0xe1, 0x91, 0x13, 0x9b, 0xd3, 0x99, 0x00, 0xef, 0x51, 0xf7, 0xa0, 0xe6, 0x6f, 0x2f, 0xa2, 0xe2,
	0x77, 0x9e, 0x4f, 0xc5, 0xdf, 0xb9, 0x33, 0x7f, 0x40, 0x2e, 0x00, 0xb6, 0xee, 0x55, 0xfc, 0x8e,
	0x9f, 0xde, 0x22, 0xb0, 0xfb, 0x31, 0xa8, 0xf6, 0x63, 0xf0, 0xbe, 0xdc, 0x8f, 0xfe, 0xe0, 0xed,
	0xe5, 0x97, 0x8b, 0x38, 0x51, 0x4b, 0x1d, 0x06, 0x77, 0x3c, 0xa3, 0x97, 0x52, 0x2f, 0xd9, 0x73,
	0x46, 0x3f, 0x15, 0x3c, 0x2e, 0x58, 0x96, 0x25, 0x79, 0x7c, 0x63, 0xae, 0xf5, 0x23, 0x2b, 0x56,
	0xa8, 0x68, 0xdf, 0x32, 0x0e, 0x27, 0xa6, 0xe8, 0xab, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0,
	0xf4, 0x6e, 0x0a, 0xab, 0x05, 0x00, 0x00,
}
