// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/pkg/pb/lesson/lesson.proto

package lesson

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListLessonsRequest struct {
	CourseId             string   `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLessonsRequest) Reset()         { *m = ListLessonsRequest{} }
func (m *ListLessonsRequest) String() string { return proto.CompactTextString(m) }
func (*ListLessonsRequest) ProtoMessage()    {}
func (*ListLessonsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{0}
}

func (m *ListLessonsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLessonsRequest.Unmarshal(m, b)
}
func (m *ListLessonsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLessonsRequest.Marshal(b, m, deterministic)
}
func (m *ListLessonsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLessonsRequest.Merge(m, src)
}
func (m *ListLessonsRequest) XXX_Size() int {
	return xxx_messageInfo_ListLessonsRequest.Size(m)
}
func (m *ListLessonsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLessonsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLessonsRequest proto.InternalMessageInfo

func (m *ListLessonsRequest) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

type ListLessonsReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId             string   `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,8,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,9,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLessonsReply) Reset()         { *m = ListLessonsReply{} }
func (m *ListLessonsReply) String() string { return proto.CompactTextString(m) }
func (*ListLessonsReply) ProtoMessage()    {}
func (*ListLessonsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{1}
}

func (m *ListLessonsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLessonsReply.Unmarshal(m, b)
}
func (m *ListLessonsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLessonsReply.Marshal(b, m, deterministic)
}
func (m *ListLessonsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLessonsReply.Merge(m, src)
}
func (m *ListLessonsReply) XXX_Size() int {
	return xxx_messageInfo_ListLessonsReply.Size(m)
}
func (m *ListLessonsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLessonsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListLessonsReply proto.InternalMessageInfo

func (m *ListLessonsReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ListLessonsReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListLessonsReply) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *ListLessonsReply) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ListLessonsReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListLessonsReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *ListLessonsReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ListLessonsReply) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *ListLessonsReply) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *ListLessonsReply) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type GetLessonRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLessonRequest) Reset()         { *m = GetLessonRequest{} }
func (m *GetLessonRequest) String() string { return proto.CompactTextString(m) }
func (*GetLessonRequest) ProtoMessage()    {}
func (*GetLessonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{2}
}

func (m *GetLessonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLessonRequest.Unmarshal(m, b)
}
func (m *GetLessonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLessonRequest.Marshal(b, m, deterministic)
}
func (m *GetLessonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLessonRequest.Merge(m, src)
}
func (m *GetLessonRequest) XXX_Size() int {
	return xxx_messageInfo_GetLessonRequest.Size(m)
}
func (m *GetLessonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLessonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLessonRequest proto.InternalMessageInfo

func (m *GetLessonRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetLessonReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId             string   `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,8,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,9,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLessonReply) Reset()         { *m = GetLessonReply{} }
func (m *GetLessonReply) String() string { return proto.CompactTextString(m) }
func (*GetLessonReply) ProtoMessage()    {}
func (*GetLessonReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{3}
}

func (m *GetLessonReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLessonReply.Unmarshal(m, b)
}
func (m *GetLessonReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLessonReply.Marshal(b, m, deterministic)
}
func (m *GetLessonReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLessonReply.Merge(m, src)
}
func (m *GetLessonReply) XXX_Size() int {
	return xxx_messageInfo_GetLessonReply.Size(m)
}
func (m *GetLessonReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLessonReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLessonReply proto.InternalMessageInfo

func (m *GetLessonReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetLessonReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetLessonReply) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *GetLessonReply) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *GetLessonReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetLessonReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *GetLessonReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetLessonReply) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *GetLessonReply) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *GetLessonReply) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type CreateLessonRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	CourseId             string   `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,7,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,8,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLessonRequest) Reset()         { *m = CreateLessonRequest{} }
func (m *CreateLessonRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLessonRequest) ProtoMessage()    {}
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{4}
}

func (m *CreateLessonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLessonRequest.Unmarshal(m, b)
}
func (m *CreateLessonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLessonRequest.Marshal(b, m, deterministic)
}
func (m *CreateLessonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLessonRequest.Merge(m, src)
}
func (m *CreateLessonRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLessonRequest.Size(m)
}
func (m *CreateLessonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLessonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLessonRequest proto.InternalMessageInfo

func (m *CreateLessonRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateLessonRequest) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *CreateLessonRequest) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *CreateLessonRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateLessonRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateLessonRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateLessonRequest) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *CreateLessonRequest) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *CreateLessonRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type CreateLessonReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId             string   `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,8,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,9,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLessonReply) Reset()         { *m = CreateLessonReply{} }
func (m *CreateLessonReply) String() string { return proto.CompactTextString(m) }
func (*CreateLessonReply) ProtoMessage()    {}
func (*CreateLessonReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{5}
}

func (m *CreateLessonReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLessonReply.Unmarshal(m, b)
}
func (m *CreateLessonReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLessonReply.Marshal(b, m, deterministic)
}
func (m *CreateLessonReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLessonReply.Merge(m, src)
}
func (m *CreateLessonReply) XXX_Size() int {
	return xxx_messageInfo_CreateLessonReply.Size(m)
}
func (m *CreateLessonReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLessonReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLessonReply proto.InternalMessageInfo

func (m *CreateLessonReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CreateLessonReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateLessonReply) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *CreateLessonReply) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *CreateLessonReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateLessonReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *CreateLessonReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CreateLessonReply) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *CreateLessonReply) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *CreateLessonReply) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type UpdateLessonRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId             string   `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,7,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,9,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,10,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLessonRequest) Reset()         { *m = UpdateLessonRequest{} }
func (m *UpdateLessonRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateLessonRequest) ProtoMessage()    {}
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{6}
}

func (m *UpdateLessonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLessonRequest.Unmarshal(m, b)
}
func (m *UpdateLessonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLessonRequest.Marshal(b, m, deterministic)
}
func (m *UpdateLessonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLessonRequest.Merge(m, src)
}
func (m *UpdateLessonRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateLessonRequest.Size(m)
}
func (m *UpdateLessonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLessonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLessonRequest proto.InternalMessageInfo

func (m *UpdateLessonRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateLessonRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateLessonRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateLessonRequest) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *UpdateLessonRequest) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *UpdateLessonRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateLessonRequest) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateLessonRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UpdateLessonRequest) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *UpdateLessonRequest) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *UpdateLessonRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type UpdateLessonReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId             string   `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	SequenceNumber       int64    `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Introduction         string   `protobuf:"bytes,6,opt,name=introduction,proto3" json:"introduction,omitempty"`
	Body                 string   `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	DefaultCode          string   `protobuf:"bytes,8,opt,name=default_code,json=defaultCode,proto3" json:"default_code,omitempty"`
	AnswerCode           string   `protobuf:"bytes,9,opt,name=answer_code,json=answerCode,proto3" json:"answer_code,omitempty"`
	Language             string   `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateLessonReply) Reset()         { *m = UpdateLessonReply{} }
func (m *UpdateLessonReply) String() string { return proto.CompactTextString(m) }
func (*UpdateLessonReply) ProtoMessage()    {}
func (*UpdateLessonReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{7}
}

func (m *UpdateLessonReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateLessonReply.Unmarshal(m, b)
}
func (m *UpdateLessonReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateLessonReply.Marshal(b, m, deterministic)
}
func (m *UpdateLessonReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateLessonReply.Merge(m, src)
}
func (m *UpdateLessonReply) XXX_Size() int {
	return xxx_messageInfo_UpdateLessonReply.Size(m)
}
func (m *UpdateLessonReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateLessonReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateLessonReply proto.InternalMessageInfo

func (m *UpdateLessonReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateLessonReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateLessonReply) GetCourseId() string {
	if m != nil {
		return m.CourseId
	}
	return ""
}

func (m *UpdateLessonReply) GetSequenceNumber() int64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *UpdateLessonReply) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateLessonReply) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UpdateLessonReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UpdateLessonReply) GetDefaultCode() string {
	if m != nil {
		return m.DefaultCode
	}
	return ""
}

func (m *UpdateLessonReply) GetAnswerCode() string {
	if m != nil {
		return m.AnswerCode
	}
	return ""
}

func (m *UpdateLessonReply) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type DeleteLessonRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteLessonRequest) Reset()         { *m = DeleteLessonRequest{} }
func (m *DeleteLessonRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteLessonRequest) ProtoMessage()    {}
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d253881d86ed08c, []int{8}
}

func (m *DeleteLessonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteLessonRequest.Unmarshal(m, b)
}
func (m *DeleteLessonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteLessonRequest.Marshal(b, m, deterministic)
}
func (m *DeleteLessonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteLessonRequest.Merge(m, src)
}
func (m *DeleteLessonRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteLessonRequest.Size(m)
}
func (m *DeleteLessonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteLessonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteLessonRequest proto.InternalMessageInfo

func (m *DeleteLessonRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteLessonRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*ListLessonsRequest)(nil), "lesson.ListLessonsRequest")
	proto.RegisterType((*ListLessonsReply)(nil), "lesson.ListLessonsReply")
	proto.RegisterType((*GetLessonRequest)(nil), "lesson.GetLessonRequest")
	proto.RegisterType((*GetLessonReply)(nil), "lesson.GetLessonReply")
	proto.RegisterType((*CreateLessonRequest)(nil), "lesson.CreateLessonRequest")
	proto.RegisterType((*CreateLessonReply)(nil), "lesson.CreateLessonReply")
	proto.RegisterType((*UpdateLessonRequest)(nil), "lesson.UpdateLessonRequest")
	proto.RegisterType((*UpdateLessonReply)(nil), "lesson.UpdateLessonReply")
	proto.RegisterType((*DeleteLessonRequest)(nil), "lesson.DeleteLessonRequest")
}

func init() {
	proto.RegisterFile("internal/pkg/pb/lesson/lesson.proto", fileDescriptor_3d253881d86ed08c)
}

var fileDescriptor_3d253881d86ed08c = []byte{
	// 591 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x96, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0x1b, 0x27, 0x71, 0xe2, 0x97, 0xa8, 0x94, 0x29, 0x2a, 0xc6, 0x59, 0x50, 0x8c, 0x04,
	0xdd, 0x60, 0xf3, 0xe7, 0x00, 0x55, 0x09, 0x55, 0xa9, 0x54, 0x10, 0x8a, 0xc4, 0x86, 0x4d, 0x64,
	0xc7, 0xaf, 0xae, 0x15, 0xc7, 0x63, 0xc6, 0x33, 0x42, 0x39, 0x0d, 0x67, 0x40, 0x70, 0x0c, 0xae,
	0xc2, 0x1d, 0x90, 0x67, 0xe2, 0x24, 0x6e, 0x8d, 0x13, 0xb1, 0xce, 0x2a, 0x7e, 0xef, 0x7d, 0xfe,
	0x64, 0xff, 0xf4, 0xc5, 0xf3, 0xe0, 0x69, 0x94, 0x70, 0x64, 0x89, 0x17, 0xbb, 0xe9, 0x34, 0x74,
	0x53, 0xdf, 0x8d, 0x31, 0xcb, 0x68, 0xb2, 0xf8, 0x71, 0x52, 0x46, 0x39, 0x25, 0xba, 0xaa, 0xac,
	0x41, 0x48, 0x69, 0x18, 0xa3, 0x2b, 0xbb, 0xbe, 0xb8, 0x76, 0x71, 0x96, 0xf2, 0xb9, 0x12, 0xd9,
	0xaf, 0x80, 0x5c, 0x45, 0x19, 0xbf, 0x92, 0xd2, 0x6c, 0x84, 0x5f, 0x05, 0x66, 0x9c, 0x0c, 0xc0,
	0x98, 0x50, 0xc1, 0x32, 0x1c, 0x47, 0x81, 0xd9, 0x38, 0x6e, 0x9c, 0x18, 0xa3, 0xae, 0x6a, 0x5c,
	0x06, 0xf6, 0x4f, 0x0d, 0x0e, 0x4a, 0xf7, 0xa4, 0xf1, 0x9c, 0x10, 0x68, 0x09, 0xb1, 0x14, 0xcb,
	0x6b, 0xf2, 0x10, 0x3a, 0x22, 0x43, 0x96, 0x7b, 0x68, 0xb2, 0xad, 0xe7, 0xe5, 0x65, 0x50, 0xb6,
	0x6f, 0x96, 0xed, 0xc9, 0x73, 0xb8, 0x97, 0xe5, 0x8f, 0x91, 0x4c, 0x70, 0x9c, 0x88, 0x99, 0x8f,
	0xcc, 0x6c, 0x1d, 0x37, 0x4e, 0x9a, 0xa3, 0xfd, 0xa2, 0xfd, 0x51, 0x76, 0xc9, 0x03, 0x68, 0xf3,
	0x88, 0xc7, 0x68, 0xb6, 0xa5, 0x83, 0x2a, 0x88, 0x0d, 0xfd, 0x28, 0xe1, 0x8c, 0x06, 0x62, 0xc2,
	0x23, 0x9a, 0x98, 0xba, 0x1c, 0x96, 0x7a, 0xf9, 0xc3, 0xfa, 0x34, 0x98, 0x9b, 0x1d, 0xf5, 0xb0,
	0xf9, 0x35, 0x79, 0x02, 0xfd, 0x00, 0xaf, 0x3d, 0x11, 0xf3, 0xf1, 0x84, 0x06, 0x68, 0x76, 0xe5,
	0xac, 0xb7, 0xe8, 0x0d, 0x69, 0x80, 0xe4, 0x31, 0xf4, 0xbc, 0x24, 0xfb, 0x86, 0x4c, 0x29, 0x0c,
	0xa9, 0x00, 0xd5, 0x92, 0x02, 0x0b, 0xba, 0xb1, 0x97, 0x84, 0xc2, 0x0b, 0xd1, 0x04, 0xf5, 0x5a,
	0x45, 0x6d, 0x3f, 0x83, 0x83, 0x0b, 0x5c, 0x30, 0x2b, 0x30, 0x57, 0x40, 0xb3, 0x7f, 0x68, 0xb0,
	0xbf, 0x26, 0xdc, 0xb1, 0xdd, 0x82, 0xed, 0x77, 0x0d, 0x0e, 0x87, 0x0c, 0x3d, 0x8e, 0x65, 0xbe,
	0xf9, 0x5b, 0xd0, 0x29, 0x26, 0x0b, 0x72, 0xaa, 0x28, 0x13, 0xd2, 0x36, 0x13, 0x6a, 0xd6, 0x13,
	0x6a, 0xd5, 0x11, 0x6a, 0xd7, 0x10, 0xd2, 0x6b, 0x08, 0x75, 0x36, 0x12, 0xea, 0xd6, 0x12, 0x32,
	0x6e, 0x11, 0xfa, 0xa5, 0xc1, 0xfd, 0x32, 0xa1, 0x5d, 0xb0, 0xb6, 0x08, 0xd6, 0x6f, 0x0d, 0x0e,
	0x3f, 0xa7, 0xc1, 0x96, 0xc1, 0x2a, 0x70, 0x6a, 0xd5, 0x38, 0x9b, 0xff, 0xc6, 0xd9, 0xda, 0x8c,
	0xb3, 0x5d, 0x8f, 0x53, 0xaf, 0xc3, 0xd9, 0xa9, 0xc1, 0xd9, 0xad, 0xc1, 0x69, 0x6c, 0xc4, 0x09,
	0xb5, 0x38, 0x7b, 0x15, 0x29, 0x2c, 0xe3, 0xdc, 0xa5, 0x70, 0x8b, 0x14, 0x9e, 0xc2, 0xe1, 0x3b,
	0x8c, 0xf1, 0xbf, 0x43, 0xf8, 0xfa, 0x8f, 0x06, 0xba, 0xba, 0x97, 0x5c, 0x40, 0x6f, 0xed, 0xec,
	0x26, 0x96, 0xb3, 0x58, 0x19, 0xee, 0x2e, 0x01, 0x96, 0x59, 0x39, 0x4b, 0xe3, 0xb9, 0xbd, 0xf7,
	0xb2, 0x41, 0x4e, 0xc1, 0x58, 0x1e, 0x53, 0x64, 0x29, 0xbd, 0x7d, 0xc4, 0x59, 0x47, 0x15, 0x13,
	0x69, 0x41, 0xde, 0x43, 0x7f, 0xfd, 0x8b, 0x44, 0x06, 0x85, 0xb2, 0xe2, 0x4b, 0x6e, 0x3d, 0xaa,
	0x1e, 0x2e, 0x9d, 0xd6, 0x53, 0xb5, 0x72, 0xaa, 0xf8, 0xeb, 0xae, 0x9c, 0xee, 0x04, 0xd1, 0xde,
	0x23, 0xe7, 0xd0, 0x5f, 0x27, 0xbd, 0x72, 0xaa, 0xe0, 0x6f, 0x1d, 0x39, 0x6a, 0xb1, 0x72, 0x8a,
	0xc5, 0xca, 0x39, 0xcf, 0x17, 0x2b, 0x7b, 0xef, 0xed, 0xf0, 0xcb, 0x59, 0x18, 0xf1, 0x1b, 0xe1,
	0x3b, 0x13, 0x3a, 0x73, 0xcf, 0x32, 0x71, 0xe3, 0xbd, 0xf0, 0xdc, 0x4f, 0x8c, 0x86, 0xcc, 0x9b,
	0xcd, 0xa2, 0x24, 0x54, 0x46, 0x1f, 0x3c, 0x36, 0x45, 0xee, 0x56, 0xef, 0x72, 0xbe, 0x2e, 0x6d,
	0xdf, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xf6, 0x60, 0x92, 0xec, 0x09, 0x00, 0x00,
}
