name: Deploy to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{secrets.SKHOLE_GITHUB_TOKEN}}
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: setup terraform
      uses: hashicorp/setup-terraform@v1.3.2
      
    - name: terraform init
      id: init
      working-directory: ./deployments/terraform
      run: terraform init
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: terraform-apply
      uses: dflook/terraform-apply@v1.29.1
      with:
        path: ./deployments/terraform
        variables: |
          jdoodle_client_id = ${{ secrets.JDOODLE_CLIENT_ID }}
          jdoodle_client_secret = ${{ secrets.JDOODLE_CLIENT_SECRET }}
